apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: ghcr.io/jschirad/simple-app:staging
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "staging"