name: CI/CD Build and Deploy

on:
  push:
    branches: [ "dev", "staging", "main" ]

jobs:
  build-deploy:
    runs-on: self-hosted
    permissions:
      contents: write
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/simple-app
      ENVIRONMENT: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          echo "Building and pushing image for environment: $ENVIRONMENT"
          docker build -t $IMAGE_NAME:${{ env.ENVIRONMENT }} .
          docker push $IMAGE_NAME:${{ env.ENVIRONMENT }}

      - name: Update deployment image
        run: |
          sed -i '' "s|image: .*|image: $IMAGE_NAME:${{ env.ENVIRONMENT }}|" k8s/deployment.yaml
          # update namespace
          sed -i '' "s|namespace: .*|namespace: ${{ env.ENVIRONMENT }}|" k8s/deployment.yaml
          # update environment variable
          sed -i '' "s|value: \".*\"|value: \"${{ env.ENVIRONMENT }}\"|" k8s/deployment.yaml
          # update the service file
          sed -i '' "s|namespace: .*|namespace: ${{ env.ENVIRONMENT }}|" k8s/service.yaml

      - name: Apply manifests to Kubernetes (optional)
        if: env.ENVIRONMENT != 'main'
        run: |
          echo "Deploying to $ENVIRONMENT environment"
          kubectl apply -f k8s/