name: CI/CD Build and Deploy

on:
  push:
    branches: [ "dev", "staging", "main" ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/simple-app
  ENVIRONMENT: ${{ github.ref_name }}

jobs:
  # Job 1: Build and Test
  build:
    name: 🔨 Build & Test
    runs-on: self-hosted
    outputs:
      image-tag: ${{ env.ENVIRONMENT }}
      image-name: ${{ env.IMAGE_NAME }}
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔍 Validate Dockerfile
        run: |
          echo "✅ Validating Dockerfile..."
          # Check if Dockerfile exists
          if [ ! -f "Dockerfile" ]; then
            echo "❌ Dockerfile not found!"
            exit 1
          fi
          # Validate Dockerfile syntax using hadolint (if available) or basic checks
          echo "📋 Dockerfile found and readable"
          echo "🔍 Basic validation completed"

      - name: 📦 Build Docker image
        run: |
          echo "🔨 Building image for environment: $ENVIRONMENT"
          docker build -t $IMAGE_NAME:$ENVIRONMENT .

  # Job 2: Push to Registry
  push:
    name: 🚀 Push to Registry
    runs-on: self-hosted
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔑 Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Build and push Docker image
        run: |
          echo "🚀 Building and pushing image: $IMAGE_NAME:$ENVIRONMENT"
          docker build -t $IMAGE_NAME:$ENVIRONMENT .
          docker push $IMAGE_NAME:$ENVIRONMENT

  # Job 3: Update Manifests
  update-manifests:
    name: 📝 Update K8s Manifests
    runs-on: self-hosted
    needs: push
    permissions:
      contents: write
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: 📝 Update deployment manifests
        run: |
          echo "📝 Updating manifests for environment: $ENVIRONMENT"
          # Update image
          sed -i '' "s|image: .*|image: $IMAGE_NAME:$ENVIRONMENT|" k8s/deployment.yaml
          # Update namespace
          sed -i '' "s|namespace: .*|namespace: $ENVIRONMENT|" k8s/deployment.yaml
          # Update environment variable
          sed -i '' "s|value: \".*\"|value: \"$ENVIRONMENT\"|" k8s/deployment.yaml
          # Update service namespace
          sed -i '' "s|namespace: .*|namespace: $ENVIRONMENT|" k8s/service.yaml

      - name: 💾 Commit manifest updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/
          if git diff --staged --quiet; then
            echo "📝 No changes to commit"
          else
            git commit -m "🚀 Update manifests for $ENVIRONMENT environment - $IMAGE_NAME:$ENVIRONMENT"
            git push origin $ENVIRONMENT
          fi

  # Job 4: Deploy to Kubernetes
  deploy:
    name: 🚀 Deploy to K8s
    runs-on: self-hosted
    needs: update-manifests
    if: github.ref_name != 'main'
    environment: ${{ github.ref_name }}
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          clean: true
      - name: 🚀 Deploy to Kubernetes
        run: |
          echo "🚀 Deploying to $ENVIRONMENT environment..."
          kubectl apply -f k8s/
          echo "✅ Deployment completed for $ENVIRONMENT!"

      - name: 📊 Check deployment status
        run: |
          echo "📊 Checking deployment status..."
          kubectl get pods -n $ENVIRONMENT
          kubectl get services -n $ENVIRONMENT